import type { Challenge } from '../types'

/**
 * 25 retos de HTML, en el mismo orden en que la Guía 1 enseña los temas.
 * Del 1 al 8 son fáciles, del 9 al 17 medios, del 18 al 25 difíciles.
 */
export const HTML_CHALLENGES: Challenge[] = [
  {
    id: 'html-01',
    lang: 'html',
    n: 1,
    title: 'El primer grito',
    brief:
      'Toda página web del mundo empezó con una línea. Esta es la tuya. Escribe un título grande, del más grande que existe, que diga exactamente: Hola mundo',
    goal: ['Una etiqueta h1', 'Que diga Hola mundo'],
    starter: '',
    hint: 'Los títulos grandes se escriben con h1, y como envuelven contenido, van en pareja: una etiqueta que abre y una que cierra con barra inclinada.',
    skeleton: '<__>Hola mundo</__>',
    solution: '<h1>Hola mundo</h1>',
    tests: [
      { t: 'exists', sel: 'h1', msg: 'Debe haber una etiqueta h1' },
      { t: 'text', sel: 'h1', eq: 'Hola mundo', msg: 'El h1 debe decir exactamente: Hola mundo' },
    ],
  },
  {
    id: 'html-02',
    lang: 'html',
    n: 2,
    title: 'Título y párrafo',
    brief:
      'Un título solo se ve triste. Ponle un párrafo debajo para que tenga con quién hablar. El título dice Mi página y el párrafo dice Estoy aprendiendo HTML.',
    goal: ['Un h1 que diga Mi página', 'Debajo, un p que diga Estoy aprendiendo HTML'],
    starter: '',
    hint: 'La etiqueta de párrafo es la letra p. Se abre y se cierra igual que el h1.',
    skeleton: '<h1>__</h1>\n<__>Estoy aprendiendo HTML</__>',
    solution: '<h1>Mi página</h1>\n<p>Estoy aprendiendo HTML</p>',
    tests: [
      { t: 'text', sel: 'h1', eq: 'Mi página', msg: 'El h1 debe decir: Mi página' },
      { t: 'text', sel: 'p', eq: 'Estoy aprendiendo HTML', msg: 'El p debe decir: Estoy aprendiendo HTML' },
    ],
  },
  {
    id: 'html-03',
    lang: 'html',
    n: 3,
    title: 'La escalera de títulos',
    brief:
      'Los títulos van del h1 al h6, de más grande a más pequeño, como una escalera que baja. Construye los tres primeros escalones.',
    goal: ['Un h1 que diga Nivel 1', 'Un h2 que diga Nivel 2', 'Un h3 que diga Nivel 3'],
    starter: '',
    hint: 'Es la misma etiqueta cambiando el número: h1, h2, h3. Fíjate en cerrar cada una con su mismo número.',
    skeleton: '<h1>Nivel 1</h1>\n<__>Nivel 2</__>\n<__>Nivel 3</__>',
    solution: '<h1>Nivel 1</h1>\n<h2>Nivel 2</h2>\n<h3>Nivel 3</h3>',
    tests: [
      { t: 'text', sel: 'h1', eq: 'Nivel 1', msg: 'Falta el h1 que diga Nivel 1' },
      { t: 'text', sel: 'h2', eq: 'Nivel 2', msg: 'Falta el h2 que diga Nivel 2' },
      { t: 'text', sel: 'h3', eq: 'Nivel 3', msg: 'Falta el h3 que diga Nivel 3' },
    ],
  },
  {
    id: 'html-04',
    lang: 'html',
    n: 4,
    title: 'Resaltar sin colores',
    brief:
      'HTML no pinta nada, pero sí puede decir qué es importante. Escribe un párrafo que diga: Me gusta el helado de vainilla. La palabra helado va marcada como importante y la palabra vainilla va marcada con énfasis.',
    goal: [
      'Un p con la frase completa',
      'La palabra helado dentro de strong',
      'La palabra vainilla dentro de em',
    ],
    starter: '<p>Me gusta el helado de vainilla.</p>',
    hint: 'strong es para lo importante (sale en negrilla) y em es para el énfasis (sale en cursiva). Van metidas dentro del párrafo, envolviendo solo esa palabra.',
    skeleton: '<p>Me gusta el <__>helado</__> de <__>vainilla</__>.</p>',
    solution: '<p>Me gusta el <strong>helado</strong> de <em>vainilla</em>.</p>',
    tests: [
      { t: 'text', sel: 'p', has: 'Me gusta el helado de vainilla', msg: 'El párrafo debe decir: Me gusta el helado de vainilla.' },
      { t: 'text', sel: 'p strong', eq: 'helado', msg: 'La palabra helado debe estar dentro de un strong, dentro del párrafo' },
      { t: 'text', sel: 'p em', eq: 'vainilla', msg: 'La palabra vainilla debe estar dentro de un em, dentro del párrafo' },
    ],
  },
  {
    id: 'html-05',
    lang: 'html',
    n: 5,
    title: 'Las dos que van solas',
    brief:
      'Hay etiquetas que no envuelven nada y por eso se escriben solas, sin pareja. Usa las dos más famosas: una que parte un renglón por la mitad y otra que dibuja una línea separadora.',
    goal: [
      'Un párrafo que diga Línea uno, luego un salto de línea, y luego Línea dos',
      'Después del párrafo, una línea horizontal separadora',
    ],
    starter: '<p>Línea uno Línea dos</p>',
    hint: 'El salto de línea es br y la línea separadora es hr. Ninguna de las dos se cierra.',
    skeleton: '<p>Línea uno<__>Línea dos</p>\n<__>',
    solution: '<p>Línea uno<br>Línea dos</p>\n<hr>',
    tests: [
      { t: 'exists', sel: 'p br', msg: 'Falta el br dentro del párrafo' },
      { t: 'text', sel: 'p', has: 'Línea uno', msg: 'El párrafo debe contener Línea uno' },
      { t: 'text', sel: 'p', has: 'Línea dos', msg: 'El párrafo debe contener Línea dos' },
      { t: 'exists', sel: 'hr', msg: 'Falta el hr después del párrafo' },
    ],
  },
  {
    id: 'html-06',
    lang: 'html',
    n: 6,
    title: 'Lista de antojos',
    brief:
      'Cuando el orden no importa, se usa una lista con viñetas. Ponle un título h3 que diga Mis comidas favoritas y debajo una lista con tres cosas: Pizza, Arepa y Helado.',
    goal: ['Un h3 que diga Mis comidas favoritas', 'Una lista con viñetas', 'Tres elementos: Pizza, Arepa, Helado'],
    starter: '<h3>Mis comidas favoritas</h3>',
    hint: 'La lista con viñetas es ul (unordered list) y cada renglón de la lista es un li (list item), que también se cierra.',
    skeleton: '<h3>Mis comidas favoritas</h3>\n<__>\n  <__>Pizza</__>\n  <li>Arepa</li>\n  <li>Helado</li>\n</__>',
    solution: '<h3>Mis comidas favoritas</h3>\n<ul>\n  <li>Pizza</li>\n  <li>Arepa</li>\n  <li>Helado</li>\n</ul>',
    tests: [
      { t: 'text', sel: 'h3', eq: 'Mis comidas favoritas', msg: 'Falta el h3 con el título' },
      { t: 'exists', sel: 'ul', msg: 'Falta la lista con viñetas (ul)' },
      { t: 'count', sel: 'ul li', eq: 3, msg: 'La lista debe tener exactamente 3 elementos li' },
      { t: 'text', sel: 'ul li', eq: 'Pizza', msg: 'Falta un li que diga Pizza' },
      { t: 'text', sel: 'ul li', eq: 'Arepa', msg: 'Falta un li que diga Arepa' },
      { t: 'text', sel: 'ul li', eq: 'Helado', msg: 'Falta un li que diga Helado' },
    ],
  },
  {
    id: 'html-07',
    lang: 'html',
    n: 7,
    title: 'Los pasos en orden',
    brief:
      'Aquí el orden sí importa: nadie se cepilla los dientes antes de desayunar. Haz una lista numerada con estos cuatro pasos, en este orden: Sonar la alarma, Desayunar, Cepillarme, Salir. Y ojo: los números NO se escriben a mano.',
    goal: ['Una lista numerada', 'Cuatro elementos, en el orden dado'],
    starter: '',
    hint: 'La lista numerada es ol (ordered list). Los números los pone el navegador solo: si los escribes tú, salen dos veces.',
    skeleton: '<__>\n  <li>Sonar la alarma</li>\n  <li>__</li>\n  <li>__</li>\n  <li>__</li>\n</__>',
    solution: '<ol>\n  <li>Sonar la alarma</li>\n  <li>Desayunar</li>\n  <li>Cepillarme</li>\n  <li>Salir</li>\n</ol>',
    tests: [
      { t: 'exists', sel: 'ol', msg: 'Falta la lista numerada (ol)' },
      { t: 'count', sel: 'ol li', eq: 4, msg: 'La lista debe tener exactamente 4 elementos li' },
      { t: 'text', sel: 'ol li:nth-child(1)', eq: 'Sonar la alarma', msg: 'El primer paso debe ser: Sonar la alarma' },
      { t: 'text', sel: 'ol li:nth-child(2)', eq: 'Desayunar', msg: 'El segundo paso debe ser: Desayunar' },
      { t: 'text', sel: 'ol li:nth-child(3)', eq: 'Cepillarme', msg: 'El tercer paso debe ser: Cepillarme' },
      { t: 'text', sel: 'ol li:nth-child(4)', eq: 'Salir', msg: 'El cuarto paso debe ser: Salir' },
      { t: 'src', re: '<li>\\s*\\d+[.)]', not: true, msg: 'No escribas los números a mano: de eso se encarga el navegador' },
    ],
  },
  {
    id: 'html-08',
    lang: 'html',
    n: 8,
    title: 'Muñecas rusas',
    brief:
      'Las etiquetas se meten unas dentro de otras, pero nunca se cruzan: la última que se abre es la primera que se cierra. Escribe un párrafo que diga Este examen está muy divertido, donde solo la palabra muy quede marcada como importante.',
    goal: ['Un solo párrafo con la frase completa', 'Solo la palabra muy dentro de strong', 'El strong va dentro del p, no al revés'],
    starter: '',
    hint: 'Primero se abre el p, adentro se abre y se cierra el strong con la palabra muy, y al final se cierra el p. Si cierras el p antes que el strong, están cruzadas.',
    skeleton: '<p>Este examen está <__>muy</__> divertido</p>',
    solution: '<p>Este examen está <strong>muy</strong> divertido</p>',
    tests: [
      { t: 'count', sel: 'p', eq: 1, msg: 'Debe haber exactamente un párrafo' },
      { t: 'text', sel: 'p', eq: 'Este examen está muy divertido', msg: 'El párrafo debe decir: Este examen está muy divertido' },
      { t: 'text', sel: 'p strong', eq: 'muy', msg: 'La palabra muy debe estar dentro de un strong que esté dentro del párrafo' },
    ],
  },
  {
    id: 'html-09',
    lang: 'html',
    n: 9,
    title: 'La foto y su descripción',
    brief:
      'Una imagen necesita dos cosas obligatorias: dónde está y qué se ve en ella. Lo segundo es lo que leen las personas ciegas, así que se escribe de verdad, no con una palabra suelta. Muestra la imagen perro.jpg con 250 píxeles de ancho.',
    goal: [
      'Una etiqueta img',
      'El atributo src con el valor perro.jpg',
      'Un alt que describa la foto (mínimo 8 letras)',
      'Un width de 250',
    ],
    starter: '',
    hint: 'img no se cierra. Los atributos van dentro de la etiqueta de apertura, con el formato nombre="valor". El de la descripción se llama alt.',
    skeleton: '<img src="__" alt="__" width="__">',
    solution: '<img src="perro.jpg" alt="Mi perro Rocky dormido en el sofá" width="250">',
    tests: [
      { t: 'exists', sel: 'img', msg: 'Falta la etiqueta img' },
      { t: 'attr', sel: 'img', name: 'src', eq: 'perro.jpg', msg: 'El src debe ser perro.jpg' },
      { t: 'attr', sel: 'img', name: 'alt', minLen: 8, msg: 'Falta el alt, o es muy corto: describe de verdad qué se ve en la foto' },
      { t: 'attr', sel: 'img', name: 'width', eq: '250', msg: 'Falta el atributo width con valor 250' },
    ],
  },
  {
    id: 'html-10',
    lang: 'html',
    n: 10,
    title: 'El ancla',
    brief:
      'La letra a viene de anchor, que en inglés es ancla: es lo que amarra una página con otra. Crea un enlace que diga Ir a Wikipedia y que lleve a https://es.wikipedia.org',
    goal: ['Una etiqueta a', 'El href apuntando a https://es.wikipedia.org', 'El texto visible: Ir a Wikipedia'],
    starter: '',
    hint: 'El atributo que dice a dónde lleva se llama href, y el texto que se ve va entre la etiqueta que abre y la que cierra.',
    skeleton: '<a __="https://es.wikipedia.org">__</a>',
    solution: '<a href="https://es.wikipedia.org">Ir a Wikipedia</a>',
    tests: [
      { t: 'exists', sel: 'a', msg: 'Falta la etiqueta a' },
      { t: 'attr', sel: 'a', name: 'href', eq: 'https://es.wikipedia.org', msg: 'El href debe ser https://es.wikipedia.org (con el https:// completo)' },
      { t: 'text', sel: 'a', eq: 'Ir a Wikipedia', msg: 'El enlace debe decir: Ir a Wikipedia' },
    ],
  },
  {
    id: 'html-11',
    lang: 'html',
    n: 11,
    title: 'Que no me saque de aquí',
    brief:
      'Cuando un enlace lleva a otro sitio, lo elegante es abrirlo en una pestaña nueva para no botar al visitante de tu página. Crea un enlace a https://github.com que diga GitHub y que se abra en otra pestaña.',
    goal: ['Un enlace a https://github.com', 'Que diga GitHub', 'Que abra en una pestaña nueva'],
    starter: '<a href="https://github.com">GitHub</a>',
    hint: 'El atributo se llama target y el valor que abre pestaña nueva empieza con guion bajo: _blank.',
    skeleton: '<a href="https://github.com" __="__">GitHub</a>',
    solution: '<a href="https://github.com" target="_blank">GitHub</a>',
    tests: [
      { t: 'attr', sel: 'a', name: 'href', eq: 'https://github.com', msg: 'El href debe ser https://github.com' },
      { t: 'text', sel: 'a', eq: 'GitHub', msg: 'El enlace debe decir: GitHub' },
      { t: 'attr', sel: 'a', name: 'target', eq: '_blank', msg: 'Falta target="_blank" para que abra en otra pestaña' },
    ],
  },
  {
    id: 'html-12',
    lang: 'html',
    n: 12,
    title: 'Un logo que lleva a alguna parte',
    brief:
      'Casi todos los logos de internet son en realidad una imagen metida dentro de un enlace. Haz eso: la imagen logo.png (con su alt) envuelta en un enlace que lleve a https://google.com',
    goal: ['Un enlace a https://google.com', 'Dentro del enlace, una img con src logo.png', 'La imagen con su alt'],
    starter: '',
    hint: 'El enlace se abre primero, la imagen va adentro y el enlace se cierra después. Como una muñeca rusa: la img es la de adentro.',
    skeleton: '<a href="__">\n  <img src="__" alt="__">\n</a>',
    solution: '<a href="https://google.com">\n  <img src="logo.png" alt="Logo de Google">\n</a>',
    tests: [
      { t: 'attr', sel: 'a', name: 'href', eq: 'https://google.com', msg: 'El enlace debe llevar a https://google.com' },
      { t: 'exists', sel: 'a img', msg: 'La imagen debe estar DENTRO del enlace' },
      { t: 'attr', sel: 'a img', name: 'src', eq: 'logo.png', msg: 'El src de la imagen debe ser logo.png' },
      { t: 'attr', sel: 'a img', name: 'alt', minLen: 3, msg: 'La imagen necesita su alt' },
    ],
  },
  {
    id: 'html-13',
    lang: 'html',
    n: 13,
    title: 'El menú',
    brief:
      'Un menú de navegación no es más que varios enlaces agrupados en una caja con nombre propio. Arma uno con tres enlaces: Inicio, Sobre mí y Contacto. Los tres apuntan al mismo sitio: index.html, perfil.html y contacto.html.',
    goal: [
      'Una etiqueta nav',
      'Tres enlaces dentro del nav',
      'Inicio → index.html, Sobre mí → perfil.html, Contacto → contacto.html',
    ],
    starter: '',
    hint: 'nav es una caja como cualquier otra: se abre, se meten los tres enlaces adentro y se cierra. Como son páginas tuyas, el href no lleva https, solo el nombre del archivo.',
    skeleton: '<__>\n  <a href="index.html">Inicio</a>\n  <a href="__">Sobre mí</a>\n  <a href="__">Contacto</a>\n</__>',
    solution: '<nav>\n  <a href="index.html">Inicio</a>\n  <a href="perfil.html">Sobre mí</a>\n  <a href="contacto.html">Contacto</a>\n</nav>',
    tests: [
      { t: 'exists', sel: 'nav', msg: 'Falta la etiqueta nav' },
      { t: 'count', sel: 'nav a', eq: 3, msg: 'El nav debe tener exactamente 3 enlaces' },
      { t: 'attr', sel: 'nav a[href="index.html"]', name: 'href', eq: 'index.html', msg: 'Falta el enlace a index.html' },
      { t: 'text', sel: 'nav a[href="index.html"]', eq: 'Inicio', msg: 'El enlace a index.html debe decir Inicio' },
      { t: 'text', sel: 'nav a[href="perfil.html"]', eq: 'Sobre mí', msg: 'Falta el enlace a perfil.html que diga Sobre mí' },
      { t: 'text', sel: 'nav a[href="contacto.html"]', eq: 'Contacto', msg: 'Falta el enlace a contacto.html que diga Contacto' },
    ],
  },
  {
    id: 'html-14',
    lang: 'html',
    n: 14,
    title: 'Una tabla de verdad',
    brief:
      'Una tabla se arma por filas, y dentro de cada fila van las celdas. La primera fila lleva encabezados; las demás, datos. Construye una tabla con la fila de encabezados Materia y Nota, y una fila de datos con Matemáticas y 4.5.',
    goal: [
      'Una etiqueta table',
      'Dos filas',
      'La primera fila con dos celdas de encabezado: Materia y Nota',
      'La segunda fila con dos celdas de datos: Matemáticas y 4.5',
    ],
    starter: '<table border="1">\n\n</table>',
    hint: 'tr es una fila completa (table row). Dentro van th para las celdas de encabezado y td para las de datos. Cuenta las celdas: las dos filas deben tener la misma cantidad.',
    skeleton: '<table border="1">\n  <__>\n    <th>Materia</th>\n    <__>Nota</__>\n  </__>\n  <tr>\n    <__>Matemáticas</__>\n    <td>4.5</td>\n  </tr>\n</table>',
    solution:
      '<table border="1">\n  <tr>\n    <th>Materia</th>\n    <th>Nota</th>\n  </tr>\n  <tr>\n    <td>Matemáticas</td>\n    <td>4.5</td>\n  </tr>\n</table>',
    tests: [
      { t: 'exists', sel: 'table', msg: 'Falta la etiqueta table' },
      { t: 'count', sel: 'table tr', eq: 2, msg: 'La tabla debe tener exactamente 2 filas (tr)' },
      { t: 'count', sel: 'table th', eq: 2, msg: 'Debe haber exactamente 2 celdas de encabezado (th)' },
      { t: 'count', sel: 'table td', eq: 2, msg: 'Debe haber exactamente 2 celdas de datos (td)' },
      { t: 'text', sel: 'th', eq: 'Materia', msg: 'Falta el encabezado Materia' },
      { t: 'text', sel: 'th', eq: 'Nota', msg: 'Falta el encabezado Nota' },
      { t: 'text', sel: 'td', eq: 'Matemáticas', msg: 'Falta la celda Matemáticas' },
      { t: 'text', sel: 'td', eq: '4.5', msg: 'Falta la celda 4.5' },
    ],
  },
  {
    id: 'html-15',
    lang: 'html',
    n: 15,
    title: 'El horario del lunes',
    brief:
      'Ahora en serio: una tabla de tres columnas con encabezados Hora, Materia y Salón, y tres filas de datos con tu horario inventado. Nueve celdas de datos en total, ni una más ni una menos.',
    goal: ['Una tabla con 4 filas en total', '3 celdas th: Hora, Materia y Salón', '9 celdas td repartidas en 3 filas'],
    starter: '<table border="1">\n\n</table>',
    hint: 'Son 4 tr: uno con los tres th, y tres más con tres td cada uno. Si alguna fila queda con menos celdas, la tabla sale torcida.',
    skeleton:
      '<table border="1">\n  <tr>\n    <th>Hora</th>\n    <th>__</th>\n    <th>__</th>\n  </tr>\n  <tr>\n    <td>7:00</td>\n    <td>__</td>\n    <td>__</td>\n  </tr>\n  <!-- faltan dos filas más -->\n</table>',
    solution:
      '<table border="1">\n  <tr>\n    <th>Hora</th>\n    <th>Materia</th>\n    <th>Salón</th>\n  </tr>\n  <tr>\n    <td>7:00</td>\n    <td>Matemáticas</td>\n    <td>201</td>\n  </tr>\n  <tr>\n    <td>8:00</td>\n    <td>Sociales</td>\n    <td>105</td>\n  </tr>\n  <tr>\n    <td>9:00</td>\n    <td>Inglés</td>\n    <td>302</td>\n  </tr>\n</table>',
    tests: [
      { t: 'count', sel: 'table tr', eq: 4, msg: 'La tabla debe tener 4 filas: una de encabezados y tres de datos' },
      { t: 'count', sel: 'table th', eq: 3, msg: 'Deben ser exactamente 3 encabezados (th)' },
      { t: 'count', sel: 'table td', eq: 9, msg: 'Deben ser exactamente 9 celdas de datos (3 filas × 3 columnas)' },
      { t: 'text', sel: 'th', eq: 'Hora', msg: 'Falta el encabezado Hora' },
      { t: 'text', sel: 'th', eq: 'Materia', msg: 'Falta el encabezado Materia' },
      { t: 'text', sel: 'th', eq: 'Salón', msg: 'Falta el encabezado Salón' },
    ],
  },
  {
    id: 'html-16',
    lang: 'html',
    n: 16,
    title: 'La casilla y su nombre',
    brief:
      'Cuando el for de un label y el id de un input coinciden, pasa algo mágico: al hacer clic en el texto se activa la casilla. Haz una casilla de texto para el nombre, con su label bien conectado.',
    goal: [
      'Un label con el atributo for igual a nombre, que diga Tu nombre:',
      'Un input de tipo text con id igual a nombre',
    ],
    starter: '',
    hint: 'El label lleva for="nombre" y el input lleva id="nombre". Tienen que estar escritos exactamente igual, letra por letra.',
    skeleton: '<label __="nombre">Tu nombre:</label>\n<input type="__" __="nombre">',
    solution: '<label for="nombre">Tu nombre:</label>\n<input type="text" id="nombre">',
    tests: [
      { t: 'exists', sel: 'label[for="nombre"]', msg: 'Falta el label con for="nombre"' },
      { t: 'text', sel: 'label', eq: 'Tu nombre:', msg: 'El label debe decir: Tu nombre:' },
      { t: 'exists', sel: 'input#nombre', msg: 'Falta el input con id="nombre"' },
      { t: 'attr', sel: 'input#nombre', name: 'type', eq: 'text', msg: 'El input debe ser de type="text"' },
    ],
  },
  {
    id: 'html-17',
    lang: 'html',
    n: 17,
    title: 'La lista desplegable',
    brief:
      'Un select es esa cajita que se despliega con opciones. Arma una para escoger color favorito, con id color y tres opciones: Azul, Rojo y Verde.',
    goal: ['Un select con id igual a color', 'Exactamente tres option adentro', 'Que digan Azul, Rojo y Verde'],
    starter: '',
    hint: 'select se abre y se cierra, y cada opción es un option que también se abre y se cierra, con el texto adentro.',
    skeleton: '<select __="color">\n  <__>Azul</__>\n  <option>__</option>\n  <option>__</option>\n</select>',
    solution: '<select id="color">\n  <option>Azul</option>\n  <option>Rojo</option>\n  <option>Verde</option>\n</select>',
    tests: [
      { t: 'exists', sel: 'select#color', msg: 'Falta el select con id="color"' },
      { t: 'count', sel: 'select option', eq: 3, msg: 'El select debe tener exactamente 3 opciones' },
      { t: 'text', sel: 'select option', eq: 'Azul', msg: 'Falta la opción Azul' },
      { t: 'text', sel: 'select option', eq: 'Rojo', msg: 'Falta la opción Rojo' },
      { t: 'text', sel: 'select option', eq: 'Verde', msg: 'Falta la opción Verde' },
    ],
  },
  {
    id: 'html-18',
    lang: 'html',
    n: 18,
    title: 'La caja grande y el botón',
    brief:
      'Para escribir un párrafo entero no sirve un input: se necesita una caja grande. Ponle un textarea con el texto de ayuda Cuéntame algo y, debajo, un botón que diga Enviar.',
    goal: [
      'Un textarea con el atributo placeholder igual a Cuéntame algo',
      'Un button que diga Enviar',
    ],
    starter: '',
    hint: 'textarea SÍ se cierra, aunque no lleve nada adentro. El texto gris de ayuda se pone con el atributo placeholder.',
    skeleton: '<textarea __="Cuéntame algo"></textarea>\n<__>Enviar</__>',
    solution: '<textarea placeholder="Cuéntame algo"></textarea>\n<button>Enviar</button>',
    tests: [
      { t: 'exists', sel: 'textarea', msg: 'Falta la etiqueta textarea' },
      { t: 'attr', sel: 'textarea', name: 'placeholder', eq: 'Cuéntame algo', msg: 'El textarea necesita placeholder="Cuéntame algo"' },
      { t: 'exists', sel: 'button', msg: 'Falta el botón' },
      { t: 'text', sel: 'button', eq: 'Enviar', msg: 'El botón debe decir: Enviar' },
    ],
  },
  {
    id: 'html-19',
    lang: 'html',
    n: 19,
    title: 'Cada dato con su casilla',
    brief:
      'El atributo type cambia por completo lo que hace un input: uno abre un calendario, otro solo deja escribir números, otro es una casilla de marcar. Pon cuatro inputs, uno de cada tipo: correo, número, fecha y casilla de marcar.',
    goal: [
      'Un input de tipo email',
      'Un input de tipo number',
      'Un input de tipo date',
      'Un input de tipo checkbox',
    ],
    starter: '',
    hint: 'Los cuatro valores del type son, en inglés: email, number, date y checkbox.',
    skeleton: '<input type="email">\n<input type="__">\n<input type="__">\n<input type="__">',
    solution: '<input type="email">\n<input type="number">\n<input type="date">\n<input type="checkbox">',
    tests: [
      { t: 'exists', sel: 'input[type="email"]', msg: 'Falta el input de type="email"' },
      { t: 'exists', sel: 'input[type="number"]', msg: 'Falta el input de type="number"' },
      { t: 'exists', sel: 'input[type="date"]', msg: 'Falta el input de type="date"' },
      { t: 'exists', sel: 'input[type="checkbox"]', msg: 'Falta el input de type="checkbox"' },
    ],
  },
  {
    id: 'html-20',
    lang: 'html',
    n: 20,
    title: 'Cajas con sticker',
    brief:
      'Una class es como el sticker que le pegas a un cuaderno: no cambia nada visualmente, pero después CSS puede decir "a todo lo que tenga este sticker, píntalo". Arma una tarjeta y marca una palabra suelta.',
    goal: [
      'Un div con class igual a tarjeta',
      'Dentro del div: un h3 que diga Mi perro y un p que diga Se llama Rocky',
      'Fuera del div, un párrafo que contenga la palabra azul dentro de un span con class igual a destacado',
    ],
    starter: '',
    hint: 'div es una caja de bloque que ocupa todo el ancho; span es una cajita que se queda dentro del renglón. La class se escribe como cualquier atributo: class="tarjeta".',
    skeleton:
      '<div __="tarjeta">\n  <h3>Mi perro</h3>\n  <p>__</p>\n</div>\n\n<p>Mi color favorito es el <__ class="__">azul</__>.</p>',
    solution:
      '<div class="tarjeta">\n  <h3>Mi perro</h3>\n  <p>Se llama Rocky</p>\n</div>\n\n<p>Mi color favorito es el <span class="destacado">azul</span>.</p>',
    tests: [
      { t: 'exists', sel: 'div.tarjeta', msg: 'Falta el div con class="tarjeta"' },
      { t: 'text', sel: 'div.tarjeta h3', eq: 'Mi perro', msg: 'Dentro del div debe ir un h3 que diga Mi perro' },
      { t: 'text', sel: 'div.tarjeta p', eq: 'Se llama Rocky', msg: 'Dentro del div debe ir un p que diga Se llama Rocky' },
      { t: 'exists', sel: 'span.destacado', msg: 'Falta el span con class="destacado"' },
      { t: 'text', sel: 'span.destacado', eq: 'azul', msg: 'El span destacado debe envolver solo la palabra azul' },
    ],
  },
  {
    id: 'html-21',
    lang: 'html',
    n: 21,
    title: 'Etiquetas con significado',
    brief:
      'Un div no dice nada sobre lo que contiene. Estas cuatro sí: le cuentan al navegador y a Google qué parte de la página es cada cosa. Arma el esqueleto visible de una página completa.',
    goal: [
      'Un header con un h1 que diga Mi página',
      'Un nav con dos enlaces',
      'Un main con un h2 que diga Sobre mí',
      'Un footer con un p que diga Hecho por mí, 2026',
    ],
    starter: '',
    hint: 'Las cuatro se comportan igual que un div: se abren, llevan cosas adentro y se cierran. Se llaman header, nav, main y footer.',
    skeleton:
      '<__>\n  <h1>Mi página</h1>\n</__>\n\n<nav>\n  <a href="#">Inicio</a>\n  <a href="#">__</a>\n</nav>\n\n<__>\n  <h2>Sobre mí</h2>\n</__>\n\n<__>\n  <p>Hecho por mí, 2026</p>\n</__>',
    solution:
      '<header>\n  <h1>Mi página</h1>\n</header>\n\n<nav>\n  <a href="#">Inicio</a>\n  <a href="#">Contacto</a>\n</nav>\n\n<main>\n  <h2>Sobre mí</h2>\n</main>\n\n<footer>\n  <p>Hecho por mí, 2026</p>\n</footer>',
    tests: [
      { t: 'text', sel: 'header h1', eq: 'Mi página', msg: 'Falta el header con un h1 que diga Mi página' },
      { t: 'count', sel: 'nav a', eq: 2, msg: 'El nav debe tener exactamente 2 enlaces' },
      { t: 'text', sel: 'main h2', eq: 'Sobre mí', msg: 'Falta el main con un h2 que diga Sobre mí' },
      { t: 'text', sel: 'footer p', eq: 'Hecho por mí, 2026', msg: 'Falta el footer con un p que diga: Hecho por mí, 2026' },
    ],
  },
  {
    id: 'html-22',
    lang: 'html',
    n: 22,
    title: 'Tres secciones',
    brief:
      'Dentro del contenido principal, cada tema va en su propia sección, y cada sección se presenta con su título. Solo puede haber un main en toda la página.',
    goal: [
      'Un main',
      'Dentro, exactamente tres section',
      'Cada section con su h2: Sobre mí, Mis gustos y Contacto',
      'Cada section con su class: sobre-mi, mis-gustos y contacto',
    ],
    starter: '<main>\n\n</main>',
    hint: 'Las tres section van una debajo de otra, todas dentro del mismo main. Cada una lleva su class y su h2 adentro.',
    skeleton:
      '<main>\n  <section class="sobre-mi">\n    <h2>Sobre mí</h2>\n  </section>\n  <section class="__">\n    <h2>__</h2>\n  </section>\n  <section class="__">\n    <h2>__</h2>\n  </section>\n</main>',
    solution:
      '<main>\n  <section class="sobre-mi">\n    <h2>Sobre mí</h2>\n  </section>\n  <section class="mis-gustos">\n    <h2>Mis gustos</h2>\n  </section>\n  <section class="contacto">\n    <h2>Contacto</h2>\n  </section>\n</main>',
    tests: [
      { t: 'count', sel: 'main', eq: 1, msg: 'Debe haber exactamente un main' },
      { t: 'count', sel: 'main section', eq: 3, msg: 'Dentro del main deben ir exactamente 3 section' },
      { t: 'text', sel: 'main section.sobre-mi h2', eq: 'Sobre mí', msg: 'Falta la section con class="sobre-mi" y su h2 Sobre mí' },
      { t: 'text', sel: 'main section.mis-gustos h2', eq: 'Mis gustos', msg: 'Falta la section con class="mis-gustos" y su h2 Mis gustos' },
      { t: 'text', sel: 'main section.contacto h2', eq: 'Contacto', msg: 'Falta la section con class="contacto" y su h2 Contacto' },
    ],
  },
  {
    id: 'html-23',
    lang: 'html',
    n: 23,
    title: 'Listas dentro de listas',
    brief:
      'Una lista puede tener otra lista adentro, pero hay un detalle que casi todos se saltan: la lista de adentro va DENTRO del li, antes de cerrarlo. Arma esta: Mascotas (con Perro y Gato adentro) y Deportes.',
    goal: [
      'Una lista ul con dos li: uno que empieza con Mascotas y otro que dice Deportes',
      'Dentro del li de Mascotas, otra ul con dos li: Perro y Gato',
    ],
    starter: '',
    hint: 'Se abre el li de Mascotas, se escribe la palabra, se abre la ul de adentro con sus dos li, se cierra esa ul, y solo ahí se cierra el li de Mascotas.',
    skeleton:
      '<ul>\n  <li>Mascotas\n    <__>\n      <li>Perro</li>\n      <li>__</li>\n    </__>\n  </li>\n  <li>__</li>\n</ul>',
    solution:
      '<ul>\n  <li>Mascotas\n    <ul>\n      <li>Perro</li>\n      <li>Gato</li>\n    </ul>\n  </li>\n  <li>Deportes</li>\n</ul>',
    tests: [
      { t: 'exists', sel: 'ul li ul', msg: 'Falta la lista de adentro: una ul dentro de un li' },
      { t: 'count', sel: 'ul li ul li', eq: 2, msg: 'La lista de adentro debe tener exactamente 2 elementos' },
      { t: 'text', sel: 'ul li ul li', eq: 'Perro', msg: 'Falta el li que diga Perro dentro de la lista interna' },
      { t: 'text', sel: 'ul li ul li', eq: 'Gato', msg: 'Falta el li que diga Gato dentro de la lista interna' },
      { t: 'text', sel: 'ul li', has: 'Mascotas', msg: 'Falta el li que empiece con Mascotas' },
      { t: 'text', sel: 'ul li', eq: 'Deportes', msg: 'Falta el li que diga Deportes en la lista de afuera' },
    ],
  },
  {
    id: 'html-24',
    lang: 'html',
    n: 24,
    title: 'La encuesta completa',
    brief:
      'Un formulario de verdad, con todo bien conectado: cada casilla con su label apuntando a su id. Si un for no coincide con su id, esa conexión no existe y el examen lo va a notar.',
    goal: [
      'Un form que envuelva todo',
      'Casilla de texto con id nombre y su label',
      'Casilla de correo con id correo y su label',
      'Un select con id deporte y tres opciones',
      'Un textarea con id comentario y su label',
      'Un button que diga Enviar respuestas',
    ],
    starter: '<form>\n\n</form>',
    hint: 'El patrón se repite cuatro veces: un label con for igual al id, y debajo la casilla con ese id. Los ids son nombre, correo, deporte y comentario.',
    skeleton:
      '<form>\n  <label for="nombre">Nombre:</label>\n  <input type="text" id="nombre">\n\n  <label for="__">Correo:</label>\n  <input type="__" id="__">\n\n  <label for="__">Deporte:</label>\n  <select id="__">\n    <option>Fútbol</option>\n    <option>__</option>\n    <option>__</option>\n  </select>\n\n  <label for="__">Comentario:</label>\n  <textarea id="__"></textarea>\n\n  <button>__</button>\n</form>',
    solution:
      '<form>\n  <label for="nombre">Nombre:</label>\n  <input type="text" id="nombre">\n\n  <label for="correo">Correo:</label>\n  <input type="email" id="correo">\n\n  <label for="deporte">Deporte:</label>\n  <select id="deporte">\n    <option>Fútbol</option>\n    <option>Baloncesto</option>\n    <option>Natación</option>\n  </select>\n\n  <label for="comentario">Comentario:</label>\n  <textarea id="comentario"></textarea>\n\n  <button>Enviar respuestas</button>\n</form>',
    tests: [
      { t: 'exists', sel: 'form', msg: 'Todo debe ir dentro de un form' },
      { t: 'exists', sel: 'form label[for="nombre"]', msg: 'Falta el label con for="nombre"' },
      { t: 'exists', sel: 'form input#nombre[type="text"]', msg: 'Falta el input de texto con id="nombre"' },
      { t: 'exists', sel: 'form label[for="correo"]', msg: 'Falta el label con for="correo"' },
      { t: 'exists', sel: 'form input#correo[type="email"]', msg: 'Falta el input de correo con id="correo"' },
      { t: 'exists', sel: 'form label[for="deporte"]', msg: 'Falta el label con for="deporte"' },
      { t: 'exists', sel: 'form select#deporte', msg: 'Falta el select con id="deporte"' },
      { t: 'count', sel: 'form select#deporte option', eq: 3, msg: 'El select de deporte debe tener exactamente 3 opciones' },
      { t: 'exists', sel: 'form label[for="comentario"]', msg: 'Falta el label con for="comentario"' },
      { t: 'exists', sel: 'form textarea#comentario', msg: 'Falta el textarea con id="comentario"' },
      { t: 'text', sel: 'form button', eq: 'Enviar respuestas', msg: 'Falta el botón que diga: Enviar respuestas' },
    ],
  },
  {
    id: 'html-25',
    lang: 'html',
    n: 25,
    title: 'JEFE FINAL — La página entera',
    brief:
      'Último reto de HTML. Aquí no se escribe solo el contenido: se escribe el documento completo, desde la primera línea. Todo lo que has aprendido, junto, en un solo archivo.',
    goal: [
      'La línea del DOCTYPE al comienzo de todo',
      'La etiqueta html con lang igual a es',
      'Un head con meta charset UTF-8 y un title que diga Mi perfil',
      'Un body con: header + h1, nav con 3 enlaces, main con una section, una ul de 3 elementos, una tabla de 2 filas, un formulario con input y button, y un footer',
    ],
    starter: '',
    hint: 'El orden es siempre el mismo: DOCTYPE, html, adentro head (lo que no se ve) y body (lo que sí se ve). Dentro del body va todo lo demás. La indentación te va a salvar de perderte.',
    skeleton:
      '<!DOCTYPE html>\n<html lang="__">\n  <head>\n    <meta charset="__">\n    <title>__</title>\n  </head>\n  <body>\n    <header><h1>__</h1></header>\n    <nav>\n      <a href="#">Inicio</a>\n      <!-- faltan dos -->\n    </nav>\n    <main>\n      <section>\n        <ul>\n          <li>__</li>\n          <!-- faltan dos -->\n        </ul>\n        <table border="1">\n          <tr><th>__</th></tr>\n          <tr><td>__</td></tr>\n        </table>\n        <form>\n          <input type="text">\n          <button>__</button>\n        </form>\n      </section>\n    </main>\n    <footer>__</footer>\n  </body>\n</html>',
    solution:
      '<!DOCTYPE html>\n<html lang="es">\n  <head>\n    <meta charset="UTF-8">\n    <title>Mi perfil</title>\n  </head>\n  <body>\n    <header><h1>Camila Rodríguez</h1></header>\n    <nav>\n      <a href="index.html">Inicio</a>\n      <a href="perfil.html">Perfil</a>\n      <a href="contacto.html">Contacto</a>\n    </nav>\n    <main>\n      <section>\n        <ul>\n          <li>Pizza</li>\n          <li>Arepa</li>\n          <li>Helado</li>\n        </ul>\n        <table border="1">\n          <tr><th>Materia</th></tr>\n          <tr><td>Matemáticas</td></tr>\n        </table>\n        <form>\n          <input type="text">\n          <button>Enviar</button>\n        </form>\n      </section>\n    </main>\n    <footer>Hecho por Camila, 2026</footer>\n  </body>\n</html>',
    tests: [
      { t: 'src', re: '^\\s*<!DOCTYPE\\s+html\\s*>', flags: 'i', msg: 'Falta la línea <!DOCTYPE html> al comienzo de todo' },
      { t: 'src', re: '<html[^>]*\\slang\\s*=\\s*"es"', flags: 'i', msg: 'La etiqueta html necesita lang="es"' },
      { t: 'exists', sel: 'head meta[charset]', msg: 'Falta el meta charset dentro del head' },
      { t: 'attr', sel: 'head meta[charset]', name: 'charset', eq: 'UTF-8', msg: 'El charset debe ser UTF-8 (si no, las tildes salen rotas)' },
      { t: 'text', sel: 'head title', eq: 'Mi perfil', msg: 'Falta el title dentro del head, que diga: Mi perfil' },
      { t: 'exists', sel: 'body header h1', msg: 'Falta el header con su h1 dentro del body' },
      { t: 'count', sel: 'body nav a', eq: 3, msg: 'El nav debe tener exactamente 3 enlaces' },
      { t: 'exists', sel: 'body main section', msg: 'Falta el main con una section adentro' },
      { t: 'count', sel: 'main ul li', eq: 3, msg: 'Falta la lista con exactamente 3 elementos dentro del main' },
      { t: 'count', sel: 'main table tr', eq: 2, msg: 'Falta la tabla con 2 filas dentro del main' },
      { t: 'exists', sel: 'main table th', msg: 'La tabla necesita al menos una celda de encabezado (th)' },
      { t: 'exists', sel: 'main form input', msg: 'Falta el formulario con un input' },
      { t: 'exists', sel: 'main form button', msg: 'Al formulario le falta el botón' },
      { t: 'exists', sel: 'body footer', msg: 'Falta el footer' },
      { t: 'text', sel: 'body footer', msg: 'El footer no puede estar vacío' },
    ],
  },
]
